sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t guytcoleman/docker-multi-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true guytcoleman/docker-multi-test npm test

after_success:
  - docker build -t guytcoleman/multi-client ./client
  - docker build -t guytcoleman/multi-nginx ./nginx
  - docker build -t guytcoleman/multi-server ./server
  - docker build -t guytcoleman/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push guytcoleman/multi-client
  - docker push guytcoleman/multi-nginx
  - docker push guytcoleman/multi-server
  - docker push guytcoleman/multi-worker
